### ISSUE TITLE
Support for Clojure 1.8

### ISSUE THREAD

**Issue by JoePython1** [jimpil/enclog#4]
Is this supported in Clojure 1.8?

**Comment by jimpil** [comment]
Hello,

I'm not actively developing enclog any more, but yeah it should work against 1.8. Let me know if you are having any problems. Cheers...

**Comment by jimpil** [comment]
it turns out you can't use it enclog 0.6.5 with clojure 1.8, and on top of that i spotted various fixes. I'll  do my best to cut a maintenance release to support latest clojure/encog . There won't be any new features though... Hope that helps.

**Comment by JoePython1** [comment]
Thank you

**Comment by jimpil** [comment]
I've just cut the 0.6.6 release which depends on Clojure 1.8 and encog 3.3...Feel free to try it :)
